export {
  isBigIntLiteral,
  isConstantNode,
  isFnExpression,
  isForStatement,
  isFunctionType,
  isIdentifier,
  isInDestructureAssignment,
  isJSXComponent,
  isMemberExpression,
  isNumericLiteral,
  isReferenced,
  isReferencedIdentifier,
  isSimpleIdentifier,
  isStaticProperty,
  isStringLiteral,
} from '@vue-jsx-vapor/compiler-rs'
