export {
  IRDynamicPropsKind,
  IRSlotsExpression,
  IRSlotType,
  type IRProp,
  type IRProps,
  type IRPropsDynamicAttribute,
  type IRPropsDynamicExpression,
  type IRPropsStatic,
  type IRSlotDynamic,
  type IRSlotDynamicBasic,
  type IRSlotDynamicConditional,
  type IRSlotDynamicLoop,
  type IRSlots,
  type IRSlotsStatic,
  type SlotBlockIRNode,
} from '@vue-jsx-vapor/compiler-rs'
