/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const __nodeFs = require('node:fs')
const __nodePath = require('node:path')
const { WASI: __nodeWASI } = require('node:wasi')
const { Worker } = require('node:worker_threads')

const {
  createOnMessage: __wasmCreateOnMessageForFsProxy,
  getDefaultContext: __emnapiGetDefaultContext,
  instantiateNapiModuleSync: __emnapiInstantiateNapiModuleSync,
} = require('@napi-rs/wasm-runtime')

const __rootDir = __nodePath.parse(process.cwd()).root

const __wasi = new __nodeWASI({
  version: 'preview1',
  env: process.env,
  preopens: {
    [__rootDir]: __rootDir,
  }
})

const __emnapiContext = __emnapiGetDefaultContext()

const __sharedMemory = new WebAssembly.Memory({
  initial: 4000,
  maximum: 65536,
  shared: true,
})

let __wasmFilePath = __nodePath.join(__dirname, 'compiler-rs.wasm32-wasi.wasm')
const __wasmDebugFilePath = __nodePath.join(__dirname, 'compiler-rs.wasm32-wasi.debug.wasm')

if (__nodeFs.existsSync(__wasmDebugFilePath)) {
  __wasmFilePath = __wasmDebugFilePath
} else if (!__nodeFs.existsSync(__wasmFilePath)) {
  try {
    __wasmFilePath = __nodePath.resolve('@vue-jsx-vapor/compiler-rs-wasm32-wasi')
  } catch {
    throw new Error('Cannot find compiler-rs.wasm32-wasi.wasm file, and @vue-jsx-vapor/compiler-rs-wasm32-wasi package is not installed.')
  }
}

const { instance: __napiInstance, module: __wasiModule, napiModule: __napiModule } = __emnapiInstantiateNapiModuleSync(__nodeFs.readFileSync(__wasmFilePath), {
  context: __emnapiContext,
  asyncWorkPoolSize: (function() {
    const threadsSizeFromEnv = Number(process.env.NAPI_RS_ASYNC_WORK_POOL_SIZE ?? process.env.UV_THREADPOOL_SIZE)
    // NaN > 0 is false
    if (threadsSizeFromEnv > 0) {
      return threadsSizeFromEnv
    } else {
      return 4
    }
  })(),
  reuseWorker: true,
  wasi: __wasi,
  onCreateWorker() {
    const worker = new Worker(__nodePath.join(__dirname, 'wasi-worker.mjs'), {
      env: process.env,
    })
    worker.onmessage = ({ data }) => {
      __wasmCreateOnMessageForFsProxy(__nodeFs)(data)
    }

    // The main thread of Node.js waits for all the active handles before exiting.
    // But Rust threads are never waited without `thread::join`.
    // So here we hack the code of Node.js to prevent the workers from being referenced (active).
    // According to https://github.com/nodejs/node/blob/19e0d472728c79d418b74bddff588bea70a403d0/lib/internal/worker.js#L415,
    // a worker is consist of two handles: kPublicPort and kHandle.
    {
      const kPublicPort = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kPublicPort")
      );
      if (kPublicPort) {
        worker[kPublicPort].ref = () => {};
      }

      const kHandle = Object.getOwnPropertySymbols(worker).find(s =>
        s.toString().includes("kHandle")
      );
      if (kHandle) {
        worker[kHandle].ref = () => {};
      }

      worker.unref();
    }
    return worker
  },
  overwriteImports(importObject) {
    importObject.env = {
      ...importObject.env,
      ...importObject.napi,
      ...importObject.emnapi,
      memory: __sharedMemory,
    }
    return importObject
  },
  beforeInit({ instance }) {
    for (const name of Object.keys(instance.exports)) {
      if (name.startsWith('__napi_register__')) {
        instance.exports[name]()
      }
    }
  },
})
module.exports = __napiModule.exports
module.exports._DynamicFlag = __napiModule.exports._DynamicFlag
module.exports.camelize = __napiModule.exports.camelize
module.exports.createSimpleExpression = __napiModule.exports.createSimpleExpression
module.exports.EMPTY_EXPRESSION = __napiModule.exports.EMPTY_EXPRESSION
module.exports.ErrorCodes = __napiModule.exports.ErrorCodes
module.exports.extractIdentifiers = __napiModule.exports.extractIdentifiers
module.exports.FragmentSymbol = __napiModule.exports.FragmentSymbol
module.exports.genBlock = __napiModule.exports.genBlock
module.exports.genBuiltinDirective = __napiModule.exports.genBuiltinDirective
module.exports.genCall = __napiModule.exports.genCall
module.exports.genCreateNodes = __napiModule.exports.genCreateNodes
module.exports.genDeclareOldRef = __napiModule.exports.genDeclareOldRef
module.exports.genDirectiveModifiers = __napiModule.exports.genDirectiveModifiers
module.exports.genDirectivesForElement = __napiModule.exports.genDirectivesForElement
module.exports.genEffect = __napiModule.exports.genEffect
module.exports.genEventHandler = __napiModule.exports.genEventHandler
module.exports.genExpression = __napiModule.exports.genExpression
module.exports.genGetTextChild = __napiModule.exports.genGetTextChild
module.exports.genIf = __napiModule.exports.genIf
module.exports.genInsertionState = __napiModule.exports.genInsertionState
module.exports.genInsertNode = __napiModule.exports.genInsertNode
module.exports.genModelHandler = __napiModule.exports.genModelHandler
module.exports.genMulti = __napiModule.exports.genMulti
module.exports.genOperation = __napiModule.exports.genOperation
module.exports.genOperations = __napiModule.exports.genOperations
module.exports.genOperationWithInsertionState = __napiModule.exports.genOperationWithInsertionState
module.exports.genSelf = __napiModule.exports.genSelf
module.exports.genSetDynamicEvents = __napiModule.exports.genSetDynamicEvents
module.exports.genSetEvent = __napiModule.exports.genSetEvent
module.exports.genSetHtml = __napiModule.exports.genSetHtml
module.exports.genSetNodes = __napiModule.exports.genSetNodes
module.exports.genSetTemplateRef = __napiModule.exports.genSetTemplateRef
module.exports.genSetText = __napiModule.exports.genSetText
module.exports.genTemplates = __napiModule.exports.genTemplates
module.exports.genVModel = __napiModule.exports.genVModel
module.exports.genVShow = __napiModule.exports.genVShow
module.exports.getDelimitersArray = __napiModule.exports.getDelimitersArray
module.exports.getDelimitersArrayNewline = __napiModule.exports.getDelimitersArrayNewline
module.exports.getDelimitersObject = __napiModule.exports.getDelimitersObject
module.exports.getDelimitersObjectNewline = __napiModule.exports.getDelimitersObjectNewline
module.exports.getExpression = __napiModule.exports.getExpression
module.exports.getLiteralExpressionValue = __napiModule.exports.getLiteralExpressionValue
module.exports.getTextLikeValue = __napiModule.exports.getTextLikeValue
module.exports.IRDynamicPropsKind = __napiModule.exports.IRDynamicPropsKind
module.exports.IRNodeTypes = __napiModule.exports.IRNodeTypes
module.exports.IRSlotType = __napiModule.exports.IRSlotType
module.exports.isBigIntLiteral = __napiModule.exports.isBigIntLiteral
module.exports.isBlockOperation = __napiModule.exports.isBlockOperation
module.exports.isConstantExpression = __napiModule.exports.isConstantExpression
module.exports.isConstantNode = __napiModule.exports.isConstantNode
module.exports.isEmptyText = __napiModule.exports.isEmptyText
module.exports.isFnExpression = __napiModule.exports.isFnExpression
module.exports.isForStatement = __napiModule.exports.isForStatement
module.exports.isFunctionType = __napiModule.exports.isFunctionType
module.exports.isIdentifier = __napiModule.exports.isIdentifier
module.exports.isInDestructureAssignment = __napiModule.exports.isInDestructureAssignment
module.exports.isJSXComponent = __napiModule.exports.isJSXComponent
module.exports.isMemberExpression = __napiModule.exports.isMemberExpression
module.exports.isNumericLiteral = __napiModule.exports.isNumericLiteral
module.exports.isReferenced = __napiModule.exports.isReferenced
module.exports.isReferencedIdentifier = __napiModule.exports.isReferencedIdentifier
module.exports.isSimpleIdentifier = __napiModule.exports.isSimpleIdentifier
module.exports.isStaticProperty = __napiModule.exports.isStaticProperty
module.exports.isStringLiteral = __napiModule.exports.isStringLiteral
module.exports.locStub = __napiModule.exports.locStub
module.exports.LOC_STUB = __napiModule.exports.LOC_STUB
module.exports.NewlineType = __napiModule.exports.NewlineType
module.exports.resolveJSXText = __napiModule.exports.resolveJSXText
module.exports.toValidAssetId = __napiModule.exports.toValidAssetId
module.exports.transform = __napiModule.exports.transform
module.exports.TS_NODE_TYPES = __napiModule.exports.TS_NODE_TYPES
module.exports.unwrapTSNode = __napiModule.exports.unwrapTSNode
module.exports.walk = __napiModule.exports.walk
module.exports.walkIdentifiers = __napiModule.exports.walkIdentifiers
