/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CodegenOptions {
  /** * Generate source map?
   * @default false
   */
  sourceMap?: boolean
  /** * Filename for source map generation.
   * Also used for self-recursive reference in templates
   * @default 'index.jsx'
   */
  filename?: string
  templates?: Array<string>
}

export declare function compile(source: string, options?: CompilerOptions | undefined | null): VaporCodegenResult

export interface CompilerError extends SyntaxError {
  code: number
  loc?: [number, number]
}

export interface CompilerOptions {
  source?: string
  templates?: Array<string>
  /** * Whether to compile components to createComponentWithFallback.
   * @default false
   */
  withFallback?: boolean
  /** * Separate option for end users to extend the native elements list
   */
  isCustomElement?: (arg: string) => boolean
  onError?: (arg: object) => void
  /** * Generate source map?
   * @default false
   */
  sourceMap?: boolean
  /** * Filename for source map generation.
   * Also used for self-recursive reference in templates
   * @default 'index.jsx'
   */
  filename?: string
}

export declare const enum ErrorCodes {
  VIfNoExpression = 28,
  VElseNoAdjacentIf = 30,
  VForNoExpression = 31,
  VForMalformedExpression = 32,
  VOnNoExpression = 35,
  VSlotMixedSlotUsage = 37,
  VSlotDuplicateSlotNames = 38,
  VSlotExtraneousDefaultSlotChildren = 39,
  VSlotMisplaced = 40,
  VModelNoExpression = 41,
  VModelMalformedExpression = 42,
  VHtmlNoExpression = 53,
  VHtmlWithChildren = 54,
  VTextNoExpression = 55,
  VTextWithChildren = 56,
  VModelOnInvalidElement = 57,
  VModelArgOnElement = 58,
  VModelOnFileInputElement = 59,
  VModelUnnecessaryValue = 60,
  VShowNoExpression = 61
}

export interface VaporCodegenResult {
  helpers: Set<string>
  templates: Array<string>
  delegates: Set<string>
  code: string
}
